# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnswersDialogGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(398, 274)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(210, 240, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSliderAca = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelSliderAca.setObjectName("labelSliderAca")
        self.gridLayout.addWidget(self.labelSliderAca, 2, 2, 1, 1)
        self.socialSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.socialSlider.setOrientation(QtCore.Qt.Horizontal)
        self.socialSlider.setObjectName("socialSlider")
        self.gridLayout.addWidget(self.socialSlider, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelSliderFin = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelSliderFin.setObjectName("labelSliderFin")
        self.gridLayout.addWidget(self.labelSliderFin, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.academicsSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.academicsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.academicsSlider.setObjectName("academicsSlider")
        self.gridLayout.addWidget(self.academicsSlider, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.answerText_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.answerText_lineEdit.setObjectName("answerText_lineEdit")
        self.gridLayout.addWidget(self.answerText_lineEdit, 1, 1, 1, 2)
        self.comment_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.comment_lineEdit.setObjectName("comment_lineEdit")
        self.gridLayout.addWidget(self.comment_lineEdit, 8, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 1)
        self.labelSliderSoc = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelSliderSoc.setObjectName("labelSliderSoc")
        self.gridLayout.addWidget(self.labelSliderSoc, 3, 2, 1, 1)
        self.financesSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.financesSlider.setOrientation(QtCore.Qt.Horizontal)
        self.financesSlider.setObjectName("financesSlider")
        self.gridLayout.addWidget(self.financesSlider, 4, 1, 1, 1)
        self.questionLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.questionLabel.setFont(font)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 0, 1, 1, 2)
        self.labelSliderHea = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelSliderHea.setObjectName("labelSliderHea")
        self.gridLayout.addWidget(self.labelSliderHea, 5, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.healthSlider = QtWidgets.QSlider(self.gridLayoutWidget)
        self.healthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.healthSlider.setObjectName("healthSlider")
        self.gridLayout.addWidget(self.healthSlider, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetButton.sizePolicy().hasHeightForWidth())
        self.resetButton.setSizePolicy(sizePolicy)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 6, 2, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelSliderAca.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Réponse"))
        self.label_2.setText(_translate("Dialog", "Question"))
        self.labelSliderFin.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "Finances"))
        self.label_5.setText(_translate("Dialog", "Social"))
        self.label_3.setText(_translate("Dialog", "Commentaire \n"
" (optionnel)"))
        self.labelSliderSoc.setText(_translate("Dialog", "0"))
        self.questionLabel.setText(_translate("Dialog", "Libellé"))
        self.labelSliderHea.setText(_translate("Dialog", "0"))
        self.label_7.setText(_translate("Dialog", "Santé"))
        self.label_4.setText(_translate("Dialog", "Académique"))
        self.resetButton.setText(_translate("Dialog", "Reset"))

