# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 538)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.date_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.date_checkBox.setChecked(False)
        self.date_checkBox.setObjectName("date_checkBox")
        self.gridLayout.addWidget(self.date_checkBox, 0, 0, 1, 1)
        self.period_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.period_checkBox.setObjectName("period_checkBox")
        self.gridLayout.addWidget(self.period_checkBox, 1, 0, 1, 1)
        self.period_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.period_comboBox.setObjectName("period_comboBox")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.period_comboBox.addItem("")
        self.gridLayout.addWidget(self.period_comboBox, 1, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 9, 19), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setTime(QtCore.QTime(0, 0, 0))
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(7917, 6, 30), QtCore.QTime(23, 59, 59)))
        self.dateEdit.setMaximumDate(QtCore.QDate(7917, 6, 30))
        self.dateEdit.setMinimumDate(QtCore.QDate(2016, 9, 19))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2016, 9, 19))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.section_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.section_checkBox.setObjectName("section_checkBox")
        self.gridLayout.addWidget(self.section_checkBox, 2, 0, 1, 1)
        self.section_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.section_comboBox.setObjectName("section_comboBox")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.section_comboBox.addItem("")
        self.gridLayout.addWidget(self.section_comboBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.financesMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.financesMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.financesMinSlider.setObjectName("financesMinSlider")
        self.gridLayout_2.addWidget(self.financesMinSlider, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.healthMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.healthMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.healthMinSlider.setObjectName("healthMinSlider")
        self.gridLayout_2.addWidget(self.healthMinSlider, 4, 1, 1, 1)
        self.tag_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tag_comboBox.setEditable(True)
        self.tag_comboBox.setObjectName("tag_comboBox")
        self.gridLayout_2.addWidget(self.tag_comboBox, 5, 1, 1, 4)
        self.academicsMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.academicsMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.academicsMaxSlider.setObjectName("academicsMaxSlider")
        self.gridLayout_2.addWidget(self.academicsMaxSlider, 1, 2, 1, 1)
        self.financesMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.financesMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.financesMaxSlider.setObjectName("financesMaxSlider")
        self.gridLayout_2.addWidget(self.financesMaxSlider, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.socialMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.socialMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.socialMaxSlider.setObjectName("socialMaxSlider")
        self.gridLayout_2.addWidget(self.socialMaxSlider, 2, 2, 1, 1)
        self.healthMax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.healthMax.sizePolicy().hasHeightForWidth())
        self.healthMax.setSizePolicy(sizePolicy)
        self.healthMax.setAlignment(QtCore.Qt.AlignCenter)
        self.healthMax.setObjectName("healthMax")
        self.gridLayout_2.addWidget(self.healthMax, 4, 4, 1, 1)
        self.acadMin = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acadMin.sizePolicy().hasHeightForWidth())
        self.acadMin.setSizePolicy(sizePolicy)
        self.acadMin.setAlignment(QtCore.Qt.AlignCenter)
        self.acadMin.setObjectName("acadMin")
        self.gridLayout_2.addWidget(self.acadMin, 1, 3, 1, 1)
        self.healthMaxSlider = QtWidgets.QSlider(self.centralwidget)
        self.healthMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.healthMaxSlider.setObjectName("healthMaxSlider")
        self.gridLayout_2.addWidget(self.healthMaxSlider, 4, 2, 1, 1)
        self.acadMax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acadMax.sizePolicy().hasHeightForWidth())
        self.acadMax.setSizePolicy(sizePolicy)
        self.acadMax.setAlignment(QtCore.Qt.AlignCenter)
        self.acadMax.setObjectName("acadMax")
        self.gridLayout_2.addWidget(self.acadMax, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.finMax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finMax.sizePolicy().hasHeightForWidth())
        self.finMax.setSizePolicy(sizePolicy)
        self.finMax.setAlignment(QtCore.Qt.AlignCenter)
        self.finMax.setObjectName("finMax")
        self.gridLayout_2.addWidget(self.finMax, 3, 4, 1, 1)
        self.socialMax = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.socialMax.sizePolicy().hasHeightForWidth())
        self.socialMax.setSizePolicy(sizePolicy)
        self.socialMax.setAlignment(QtCore.Qt.AlignCenter)
        self.socialMax.setObjectName("socialMax")
        self.gridLayout_2.addWidget(self.socialMax, 2, 4, 1, 1)
        self.healthMin = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.healthMin.sizePolicy().hasHeightForWidth())
        self.healthMin.setSizePolicy(sizePolicy)
        self.healthMin.setAlignment(QtCore.Qt.AlignCenter)
        self.healthMin.setObjectName("healthMin")
        self.gridLayout_2.addWidget(self.healthMin, 4, 3, 1, 1)
        self.socialMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.socialMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.socialMinSlider.setObjectName("socialMinSlider")
        self.gridLayout_2.addWidget(self.socialMinSlider, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.finMin = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finMin.sizePolicy().hasHeightForWidth())
        self.finMin.setSizePolicy(sizePolicy)
        self.finMin.setAlignment(QtCore.Qt.AlignCenter)
        self.finMin.setObjectName("finMin")
        self.gridLayout_2.addWidget(self.finMin, 3, 3, 1, 1)
        self.cat_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.cat_comboBox.setObjectName("cat_comboBox")
        self.gridLayout_2.addWidget(self.cat_comboBox, 6, 1, 1, 4)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.socialMin = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.socialMin.sizePolicy().hasHeightForWidth())
        self.socialMin.setSizePolicy(sizePolicy)
        self.socialMin.setAlignment(QtCore.Qt.AlignCenter)
        self.socialMin.setObjectName("socialMin")
        self.gridLayout_2.addWidget(self.socialMin, 2, 3, 1, 1)
        self.academicsMinSlider = QtWidgets.QSlider(self.centralwidget)
        self.academicsMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.academicsMinSlider.setObjectName("academicsMinSlider")
        self.gridLayout_2.addWidget(self.academicsMinSlider, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.show2_button = QtWidgets.QPushButton(self.centralwidget)
        self.show2_button.setObjectName("show2_button")
        self.gridLayout_3.addWidget(self.show2_button, 4, 1, 1, 2)
        self.question_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.question_lineEdit.setObjectName("question_lineEdit")
        self.gridLayout_3.addWidget(self.question_lineEdit, 2, 1, 1, 2)
        self.show4_button = QtWidgets.QPushButton(self.centralwidget)
        self.show4_button.setObjectName("show4_button")
        self.gridLayout_3.addWidget(self.show4_button, 6, 1, 1, 2)
        self.answer2_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.answer2_checkBox.setObjectName("answer2_checkBox")
        self.gridLayout_3.addWidget(self.answer2_checkBox, 4, 0, 1, 1)
        self.answer3_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.answer3_checkBox.setObjectName("answer3_checkBox")
        self.gridLayout_3.addWidget(self.answer3_checkBox, 5, 0, 1, 1)
        self.show3_button = QtWidgets.QPushButton(self.centralwidget)
        self.show3_button.setObjectName("show3_button")
        self.gridLayout_3.addWidget(self.show3_button, 5, 1, 1, 2)
        self.answer4_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.answer4_checkBox.setObjectName("answer4_checkBox")
        self.gridLayout_3.addWidget(self.answer4_checkBox, 6, 0, 1, 1)
        self.answer1_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.answer1_checkBox.setObjectName("answer1_checkBox")
        self.gridLayout_3.addWidget(self.answer1_checkBox, 3, 0, 1, 1)
        self.show1_button = QtWidgets.QPushButton(self.centralwidget)
        self.show1_button.setObjectName("show1_button")
        self.gridLayout_3.addWidget(self.show1_button, 3, 1, 1, 2)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout_3.addWidget(self.browseButton, 1, 1, 1, 1)
        self.imageName_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.imageName_lineEdit.setObjectName("imageName_lineEdit")
        self.gridLayout_3.addWidget(self.imageName_lineEdit, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.imageName_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.imageName_checkBox.setObjectName("imageName_checkBox")
        self.gridLayout_3.addWidget(self.imageName_checkBox, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_button.sizePolicy().hasHeightForWidth())
        self.send_button.setSizePolicy(sizePolicy)
        self.send_button.setObjectName("send_button")
        self.verticalLayout_2.addWidget(self.send_button)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLabel.sizePolicy().hasHeightForWidth())
        self.statusLabel.setSizePolicy(sizePolicy)
        self.statusLabel.setTextFormat(QtCore.Qt.PlainText)
        self.statusLabel.setScaledContents(False)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_2.addWidget(self.statusLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.date_checkBox.setText(_translate("MainWindow", "Date"))
        self.period_checkBox.setText(_translate("MainWindow", "Période"))
        self.period_comboBox.setItemText(0, _translate("MainWindow", "Début semestre 1"))
        self.period_comboBox.setItemText(1, _translate("MainWindow", "Milieu semestre 1"))
        self.period_comboBox.setItemText(2, _translate("MainWindow", "Fin semestre 1"))
        self.period_comboBox.setItemText(3, _translate("MainWindow", "Révisions 1"))
        self.period_comboBox.setItemText(4, _translate("MainWindow", "Examens 1"))
        self.period_comboBox.setItemText(5, _translate("MainWindow", "Vacances"))
        self.period_comboBox.setItemText(6, _translate("MainWindow", "Début semestre 2"))
        self.period_comboBox.setItemText(7, _translate("MainWindow", "Milieu semestre 2"))
        self.period_comboBox.setItemText(8, _translate("MainWindow", "Fin semestre 2"))
        self.period_comboBox.setItemText(9, _translate("MainWindow", "Révisions 2"))
        self.period_comboBox.setItemText(10, _translate("MainWindow", "Examens 2"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.section_checkBox.setText(_translate("MainWindow", "Section"))
        self.section_comboBox.setItemText(0, _translate("MainWindow", "PH"))
        self.section_comboBox.setItemText(1, _translate("MainWindow", "MA"))
        self.section_comboBox.setItemText(2, _translate("MainWindow", "SCGC"))
        self.section_comboBox.setItemText(3, _translate("MainWindow", "GM"))
        self.section_comboBox.setItemText(4, _translate("MainWindow", "MT"))
        self.section_comboBox.setItemText(5, _translate("MainWindow", "EL"))
        self.section_comboBox.setItemText(6, _translate("MainWindow", "MX"))
        self.section_comboBox.setItemText(7, _translate("MainWindow", "IN"))
        self.section_comboBox.setItemText(8, _translate("MainWindow", "SC"))
        self.section_comboBox.setItemText(9, _translate("MainWindow", "GC"))
        self.section_comboBox.setItemText(10, _translate("MainWindow", "SIE"))
        self.section_comboBox.setItemText(11, _translate("MainWindow", "AR"))
        self.section_comboBox.setItemText(12, _translate("MainWindow", "SV"))
        self.label_3.setText(_translate("MainWindow", "Social"))
        self.label_6.setText(_translate("MainWindow", "Range de sélection"))
        self.label_7.setText(_translate("MainWindow", "Min"))
        self.label_9.setText(_translate("MainWindow", "Tag"))
        self.healthMax.setText(_translate("MainWindow", "0"))
        self.acadMin.setText(_translate("MainWindow", "0"))
        self.acadMax.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "Académique"))
        self.label_5.setText(_translate("MainWindow", "Santé"))
        self.finMax.setText(_translate("MainWindow", "0"))
        self.socialMax.setText(_translate("MainWindow", "0"))
        self.healthMin.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "Max"))
        self.label_4.setText(_translate("MainWindow", "Finances"))
        self.finMin.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Catégorie"))
        self.socialMin.setText(_translate("MainWindow", "0"))
        self.show2_button.setText(_translate("MainWindow", "Afficher"))
        self.question_lineEdit.setPlaceholderText(_translate("MainWindow", "Posez votre question"))
        self.show4_button.setText(_translate("MainWindow", "Afficher"))
        self.answer2_checkBox.setText(_translate("MainWindow", "Réponse 2"))
        self.answer3_checkBox.setText(_translate("MainWindow", "Réponse 3"))
        self.show3_button.setText(_translate("MainWindow", "Afficher"))
        self.answer4_checkBox.setText(_translate("MainWindow", "Réponse 4"))
        self.answer1_checkBox.setText(_translate("MainWindow", "Réponse 1"))
        self.show1_button.setText(_translate("MainWindow", "Afficher"))
        self.browseButton.setText(_translate("MainWindow", "Parcourir"))
        self.imageName_lineEdit.setPlaceholderText(_translate("MainWindow", "Entrer le nom de l\'image"))
        self.label_2.setText(_translate("MainWindow", "Question"))
        self.imageName_checkBox.setText(_translate("MainWindow", "Image"))
        self.send_button.setText(_translate("MainWindow", "Envoyer!"))
        self.statusLabel.setText(_translate("MainWindow", "status"))

